# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: send_emails

on:
  schedule:
    # - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: access to secrets
      run: |
        echo "SENDER_EMAIL=$SENDER_EMAIL" >> .env
        echo "SENDER_PASSWORD=$SENDER_PASSWORD" >> .env
        echo "FIREBASE_CREDENTIALS=$FIREBASE_CREDENTIALS" >> .env
      env:
        SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        SENDER_PASSWORD: ${{secrets.SENDER_PASSWORD}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Run
      run: |
        python send_emails.py
